#!/usr/bin/env bash
#Script that shows a list of the processes that are currently running.
#Must show all processes, for all users, including those which might not have a TTY
#Display in a user-oriented format
#Show process hierarchy
ps auxf
