#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times.

for ((i = 0; i < 10; i++)); do
    echo 'Best School'
    done

#$i
#for i in {1..10}; do
#    printf "Holberton School\n"
#done
